---
- hosts: localhost
  gather_facts: true
  become: true
  connection: local
  tasks:
  - name: include all the system vars
    include_vars:
        dir: "/etc/nbs/vars"
    ignore_errors: true
  - name: driver
    include_role:
       name: nbs
       tasks_from: "{{ driver }}"

