# roles/nbs/tasks/setup.yml
---
- name: Create the seed system config file
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "/etc/nbs"
    - "/etc/nbs/vars"

- name: set nbs root
  copy:
     dest: "/etc/nbs/vars/00root.yml"
     content: |
        nbs_root: "{{ prefix }}"
  when: prefix is defined

- name: include all the system vars
  include_vars:
      dir: "/etc/nbs/vars"

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ nbs_packages }}"

- name: Create directory for PXEboot related files
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ nbs_root_directory }}"
    - "{{ nbs_iso_directory }}"
    - "{{ nbs_etc_directory }}"
    - "{{ nbs_etc_directory }}/pxe"
    - "{{ nbs_web_directory }}"
    - "{{ nbs_shares_directory }}"
    - "{{ nbs_tftp_root_directory }}"
    - "{{ nbs_pxe_path }}/pxelinux.cfg"


