---
- name: Build the DHCP Configuration File
  ansible.builtin.template:
    src: etc_dhcp_dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
  register: dhcpd_conf

- name: Allow DHCP through the firewall
  ansible.posix.firewalld:
    service: "{{ fwall }}"
    permanent: yes
    state: enabled
  loop:
    - dhcp
  loop_control:
    loop_var: fwall

- name: Enable and Start DHCPD
  ansible.builtin.service:
    name: dhcpd
    state: started
    enabled: yes

- name: Restart the DHCPD service if the configuration file changed
  when: dhcpd_conf.changed
  ansible.builtin.service:
    name: dhcpd
    state: restarted