#!/bin/bash
for i in "$@"
do
  case $i in
    -n=*|--osname=*)
	        OSNAME="${i#*=}"
		    ;;
    -a=*|--arch=*)
	        ARCH="${i#*=}"
		    ;;
    *)
	        ISO="${i#*=}"
   ;;
  esac
done
echo "$OSNAME"
echo "$ARCH"
echo "$ISO"
if [ "$OSNAME" == "" ] || [ "$ARCH" == "" ]; then
	echo "Both -n (osname) and -a (arch) are required"
	exit 1
fi
cd ..
ansible-playbook -e "osname=$OSNAME arch=$ARCH iso=$ISO driver=copycds" driver.yml
